var hierarchy =
[
    [ "PluginFrame\\Core\\Services\\ActionsLinks", "classPluginFrame_1_1Core_1_1Services_1_1ActionsLinks.html", null ],
    [ "PluginFrame\\Providers\\ActionsLinks", "classPluginFrame_1_1Providers_1_1ActionsLinks.html", null ],
    [ "PluginFrame\\Core\\Hooks\\Activation", "classPluginFrame_1_1Core_1_1Hooks_1_1Activation.html", [
      [ "PluginFrame\\Hooks\\Activation", "classPluginFrame_1_1Hooks_1_1Activation.html", null ]
    ] ],
    [ "PluginFrame\\Config\\APIbase", "classPluginFrame_1_1Config_1_1APIbase.html", null ],
    [ "PluginFrame\\Core\\API\\ApiHeaders", "classPluginFrame_1_1Core_1_1API_1_1ApiHeaders.html", null ],
    [ "PluginFrame\\Core\\API\\ApiRoutes", "classPluginFrame_1_1Core_1_1API_1_1ApiRoutes.html", null ],
    [ "PluginFrame\\Core\\Routes\\Middleware\\AuthAppPassMiddleware", "classPluginFrame_1_1Core_1_1Routes_1_1Middleware_1_1AuthAppPassMiddleware.html", null ],
    [ "PluginFrame\\Core\\Routes\\Middleware\\AuthMiddleware", "classPluginFrame_1_1Core_1_1Routes_1_1Middleware_1_1AuthMiddleware.html", null ],
    [ "PluginFrame\\Core\\Routes\\Middleware\\AuthUserPassMiddleware", "classPluginFrame_1_1Core_1_1Routes_1_1Middleware_1_1AuthUserPassMiddleware.html", null ],
    [ "PluginFrame\\Core\\DB\\Models\\BaseModel", "classPluginFrame_1_1Core_1_1DB_1_1Models_1_1BaseModel.html", [
      [ "PluginFrame\\Core\\DB\\Models\\CustomQueryModel", "classPluginFrame_1_1Core_1_1DB_1_1Models_1_1CustomQueryModel.html", null ],
      [ "PluginFrame\\Core\\DB\\Models\\JobCategory", "classPluginFrame_1_1Core_1_1DB_1_1Models_1_1JobCategory.html", null ],
      [ "PluginFrame\\Core\\DB\\Models\\JobListing", "classPluginFrame_1_1Core_1_1DB_1_1Models_1_1JobListing.html", null ]
    ] ],
    [ "PluginFrame\\Core\\Services\\Widgets\\Block", "classPluginFrame_1_1Core_1_1Services_1_1Widgets_1_1Block.html", null ],
    [ "PluginFrame\\Providers\\Widgets\\Block", "classPluginFrame_1_1Providers_1_1Widgets_1_1Block.html", null ],
    [ "PluginFrame\\Config\\Bootstrap", "classPluginFrame_1_1Config_1_1Bootstrap.html", null ],
    [ "PluginFrame\\Core\\Helpers\\BootstrapHelper", "classPluginFrame_1_1Core_1_1Helpers_1_1BootstrapHelper.html", null ],
    [ "PluginFrame\\Core\\Services\\Widgets\\Classic", "classPluginFrame_1_1Core_1_1Services_1_1Widgets_1_1Classic.html", null ],
    [ "PluginFrame\\Providers\\Widgets\\Classic", "classPluginFrame_1_1Providers_1_1Widgets_1_1Classic.html", null ],
    [ "PluginFrame\\Core\\DB\\WP\\CommentMeta", "classPluginFrame_1_1Core_1_1DB_1_1WP_1_1CommentMeta.html", null ],
    [ "PluginFrame\\Core\\DB\\WP\\Comments", "classPluginFrame_1_1Core_1_1DB_1_1WP_1_1Comments.html", null ],
    [ "PluginFrame\\REST\\Controllers\\WP\\CommentsData", "classPluginFrame_1_1REST_1_1Controllers_1_1WP_1_1CommentsData.html", null ],
    [ "PluginFrame\\Config\\Config", "classPluginFrame_1_1Config_1_1Config.html", null ],
    [ "PluginFrame\\Core\\Updater\\CoreUpdater", "classPluginFrame_1_1Core_1_1Updater_1_1CoreUpdater.html", null ],
    [ "PluginFrame\\Core\\Routes\\Middleware\\CORSMiddleware", "classPluginFrame_1_1Core_1_1Routes_1_1Middleware_1_1CORSMiddleware.html", null ],
    [ "PluginFrame\\Core\\DB\\Migrations\\CreateJobCategoriesTable", "classPluginFrame_1_1Core_1_1DB_1_1Migrations_1_1CreateJobCategoriesTable.html", null ],
    [ "PluginFrame\\Core\\DB\\Migrations\\CreateJobListingsTable", "classPluginFrame_1_1Core_1_1DB_1_1Migrations_1_1CreateJobListingsTable.html", null ],
    [ "PluginFrame\\Config\\Cron", "classPluginFrame_1_1Config_1_1Cron.html", null ],
    [ "PluginFrame\\Core\\Services\\Customize", "classPluginFrame_1_1Core_1_1Services_1_1Customize.html", null ],
    [ "PluginFrame\\Providers\\Customize", "classPluginFrame_1_1Providers_1_1Customize.html", null ],
    [ "PluginFrame\\Core\\Updater\\CustomUpdater", "classPluginFrame_1_1Core_1_1Updater_1_1CustomUpdater.html", null ],
    [ "PluginFrame\\Views\\Admin\\Dashboard", "classPluginFrame_1_1Views_1_1Admin_1_1Dashboard.html", null ],
    [ "PluginFrame\\Views\\AdminAlpine\\DashboardAlpine", "classPluginFrame_1_1Views_1_1AdminAlpine_1_1DashboardAlpine.html", null ],
    [ "PluginFrame\\Config\\DBconfig", "classPluginFrame_1_1Config_1_1DBconfig.html", null ],
    [ "PluginFrame\\Core\\DB\\Utils\\DBHelper", "classPluginFrame_1_1Core_1_1DB_1_1Utils_1_1DBHelper.html", null ],
    [ "PluginFrame\\Core\\DB\\Utils\\DBUtils", "classPluginFrame_1_1Core_1_1DB_1_1Utils_1_1DBUtils.html", null ],
    [ "PluginFrame\\Core\\Hooks\\Deactivation", "classPluginFrame_1_1Core_1_1Hooks_1_1Deactivation.html", [
      [ "PluginFrame\\Hooks\\Deactivation", "classPluginFrame_1_1Hooks_1_1Deactivation.html", null ]
    ] ],
    [ "PluginFrame\\Config\\Debug", "classPluginFrame_1_1Config_1_1Debug.html", null ],
    [ "PluginFrame\\Core\\Utilities\\Debug\\Debugger", "classPluginFrame_1_1Core_1_1Utilities_1_1Debug_1_1Debugger.html", null ],
    [ "PluginFrame\\REST\\Controllers\\DemoData", "classPluginFrame_1_1REST_1_1Controllers_1_1DemoData.html", null ],
    [ "PluginFrame\\Core\\Services\\Enqueue", "classPluginFrame_1_1Core_1_1Services_1_1Enqueue.html", null ],
    [ "PluginFrame\\Providers\\Enqueues", "classPluginFrame_1_1Providers_1_1Enqueues.html", null ],
    [ "PluginFrame\\Core\\DB\\WP\\EventsMeta", "classPluginFrame_1_1Core_1_1DB_1_1WP_1_1EventsMeta.html", null ],
    [ "PluginFrame\\Core\\Services\\Options\\Export", "classPluginFrame_1_1Core_1_1Services_1_1Options_1_1Export.html", null ],
    [ "PluginFrame\\Providers\\Options\\Export", "classPluginFrame_1_1Providers_1_1Options_1_1Export.html", null ],
    [ "PluginFrame\\Core\\Updater\\GitHubUpdater", "classPluginFrame_1_1Core_1_1Updater_1_1GitHubUpdater.html", null ],
    [ "PluginFrame\\REST\\Controllers\\HandleData", "classPluginFrame_1_1REST_1_1Controllers_1_1HandleData.html", null ],
    [ "PluginFrame\\Core\\Routes\\Helpers", "classPluginFrame_1_1Core_1_1Routes_1_1Helpers.html", null ],
    [ "PluginFrame\\Config\\HooksLoader", "classPluginFrame_1_1Config_1_1HooksLoader.html", null ],
    [ "PluginFrame\\Core\\Services\\Options\\Import", "classPluginFrame_1_1Core_1_1Services_1_1Options_1_1Import.html", null ],
    [ "PluginFrame\\Providers\\Options\\Import", "classPluginFrame_1_1Providers_1_1Options_1_1Import.html", null ],
    [ "PluginFrame\\Core\\Helpers\\LanguageTextDomain", "classPluginFrame_1_1Core_1_1Helpers_1_1LanguageTextDomain.html", null ],
    [ "PluginFrame\\Core\\DB\\WP\\Links", "classPluginFrame_1_1Core_1_1DB_1_1WP_1_1Links.html", null ],
    [ "PluginFrame\\Core\\Utilities\\PFlogs\\LogCleaner", "classPluginFrame_1_1Core_1_1Utilities_1_1PFlogs_1_1LogCleaner.html", null ],
    [ "PluginFrame\\Core\\Services\\Menus", "classPluginFrame_1_1Core_1_1Services_1_1Menus.html", null ],
    [ "PluginFrame\\Providers\\Menus", "classPluginFrame_1_1Providers_1_1Menus.html", null ],
    [ "PluginFrame\\Core\\DB\\Migrations\\Migration", "classPluginFrame_1_1Core_1_1DB_1_1Migrations_1_1Migration.html", null ],
    [ "PluginFrame\\Core\\Services\\Notice", "classPluginFrame_1_1Core_1_1Services_1_1Notice.html", null ],
    [ "PluginFrame\\Providers\\Notices", "classPluginFrame_1_1Providers_1_1Notices.html", null ],
    [ "PluginFrame\\Core\\Services\\Options\\Option", "classPluginFrame_1_1Core_1_1Services_1_1Options_1_1Option.html", null ],
    [ "PluginFrame\\Core\\DB\\WP\\Options", "classPluginFrame_1_1Core_1_1DB_1_1WP_1_1Options.html", null ],
    [ "PluginFrame\\Providers\\Options\\Options", "classPluginFrame_1_1Providers_1_1Options_1_1Options.html", null ],
    [ "PluginFrame\\REST\\Controllers\\OtherHandlers", "classPluginFrame_1_1REST_1_1Controllers_1_1OtherHandlers.html", null ],
    [ "PluginFrame\\Core\\DB\\Pagination\\PaginationManager", "classPluginFrame_1_1Core_1_1DB_1_1Pagination_1_1PaginationManager.html", null ],
    [ "PluginFrame\\Core\\Utilities\\PFlogs\\PFlogs", "classPluginFrame_1_1Core_1_1Utilities_1_1PFlogs_1_1PFlogs.html", null ],
    [ "PluginFrame\\Core\\DB\\WP\\PostMeta", "classPluginFrame_1_1Core_1_1DB_1_1WP_1_1PostMeta.html", null ],
    [ "PluginFrame\\Core\\DB\\WP\\Posts", "classPluginFrame_1_1Core_1_1DB_1_1WP_1_1Posts.html", null ],
    [ "PluginFrame\\Core\\Services\\PostTypes", "classPluginFrame_1_1Core_1_1Services_1_1PostTypes.html", null ],
    [ "PluginFrame\\Providers\\PostTypes", "classPluginFrame_1_1Providers_1_1PostTypes.html", null ],
    [ "PluginFrame\\Config\\Providers", "classPluginFrame_1_1Config_1_1Providers.html", null ],
    [ "PluginFrame\\Core\\Helpers\\ProvidersHelper", "classPluginFrame_1_1Core_1_1Helpers_1_1ProvidersHelper.html", null ],
    [ "PluginFrame\\REST\\Controllers\\PublicData", "classPluginFrame_1_1REST_1_1Controllers_1_1PublicData.html", null ],
    [ "PluginFrame\\Core\\Routes\\Middleware\\PublicMiddleware", "classPluginFrame_1_1Core_1_1Routes_1_1Middleware_1_1PublicMiddleware.html", null ],
    [ "PluginFrame\\Core\\DB\\Utils\\QueryBuilder", "classPluginFrame_1_1Core_1_1DB_1_1Utils_1_1QueryBuilder.html", null ],
    [ "PluginFrame\\Core\\Routes\\Middleware\\RateLimitMiddleware", "classPluginFrame_1_1Core_1_1Routes_1_1Middleware_1_1RateLimitMiddleware.html", null ],
    [ "PluginFrame\\Core\\Routes\\Register", "classPluginFrame_1_1Core_1_1Routes_1_1Register.html", null ],
    [ "PluginFrame\\Core\\Routes\\Middleware\\RoleMiddleware", "classPluginFrame_1_1Core_1_1Routes_1_1Middleware_1_1RoleMiddleware.html", null ],
    [ "PluginFrame\\Config\\Routes", "classPluginFrame_1_1Config_1_1Routes.html", null ],
    [ "PluginFrame\\Core\\Services\\Scheduler", "classPluginFrame_1_1Core_1_1Services_1_1Scheduler.html", null ],
    [ "PluginFrame\\Core\\Services\\ScreenHelp", "classPluginFrame_1_1Core_1_1Services_1_1ScreenHelp.html", null ],
    [ "PluginFrame\\Providers\\ScreenHelp", "classPluginFrame_1_1Providers_1_1ScreenHelp.html", null ],
    [ "PluginFrame\\Core\\DB\\Seeders\\Seeder", "classPluginFrame_1_1Core_1_1DB_1_1Seeders_1_1Seeder.html", [
      [ "PluginFrame\\Core\\DB\\Seeders\\SettingsSeeder", "classPluginFrame_1_1Core_1_1DB_1_1Seeders_1_1SettingsSeeder.html", null ]
    ] ],
    [ "PluginFrame\\Views\\Admin\\Settings", "classPluginFrame_1_1Views_1_1Admin_1_1Settings.html", null ],
    [ "PluginFrame\\Views\\AdminAlpine\\SettingsAlpine", "classPluginFrame_1_1Views_1_1AdminAlpine_1_1SettingsAlpine.html", null ],
    [ "PluginFrame\\Core\\Services\\ShortCode", "classPluginFrame_1_1Core_1_1Services_1_1ShortCode.html", null ],
    [ "PluginFrame\\Providers\\ShortCodes", "classPluginFrame_1_1Providers_1_1ShortCodes.html", null ],
    [ "PluginFrame\\Core\\Services\\Taxonomies", "classPluginFrame_1_1Core_1_1Services_1_1Taxonomies.html", null ],
    [ "PluginFrame\\Providers\\Taxonomies", "classPluginFrame_1_1Providers_1_1Taxonomies.html", null ],
    [ "PluginFrame\\Core\\DB\\WP\\TermMeta", "classPluginFrame_1_1Core_1_1DB_1_1WP_1_1TermMeta.html", null ],
    [ "PluginFrame\\Core\\DB\\WP\\TermRelationships", "classPluginFrame_1_1Core_1_1DB_1_1WP_1_1TermRelationships.html", null ],
    [ "PluginFrame\\Core\\DB\\WP\\Terms", "classPluginFrame_1_1Core_1_1DB_1_1WP_1_1Terms.html", null ],
    [ "PluginFrame\\Core\\DB\\WP\\TermTaxonomy", "classPluginFrame_1_1Core_1_1DB_1_1WP_1_1TermTaxonomy.html", null ],
    [ "PluginFrame\\REST\\Controllers\\TestData", "classPluginFrame_1_1REST_1_1Controllers_1_1TestData.html", null ],
    [ "PluginFrame\\Views\\Admin\\Tools", "classPluginFrame_1_1Views_1_1Admin_1_1Tools.html", null ],
    [ "PluginFrame\\Views\\AdminAlpine\\ToolsAlpine", "classPluginFrame_1_1Views_1_1AdminAlpine_1_1ToolsAlpine.html", null ],
    [ "PluginFrame\\Core\\Hooks\\Uninstall", "classPluginFrame_1_1Core_1_1Hooks_1_1Uninstall.html", [
      [ "PluginFrame\\Hooks\\Uninstall", "classPluginFrame_1_1Hooks_1_1Uninstall.html", null ]
    ] ],
    [ "PluginFrame\\Core\\Updater\\UpdateManager", "classPluginFrame_1_1Core_1_1Updater_1_1UpdateManager.html", null ],
    [ "PluginFrame\\Config\\Updater", "classPluginFrame_1_1Config_1_1Updater.html", null ],
    [ "PluginFrame\\Core\\Hooks\\Upgrade", "classPluginFrame_1_1Core_1_1Hooks_1_1Upgrade.html", [
      [ "PluginFrame\\Hooks\\Upgrade", "classPluginFrame_1_1Hooks_1_1Upgrade.html", null ]
    ] ],
    [ "PluginFrame\\Core\\DB\\WP\\UserMeta", "classPluginFrame_1_1Core_1_1DB_1_1WP_1_1UserMeta.html", null ],
    [ "PluginFrame\\Core\\DB\\WP\\Users", "classPluginFrame_1_1Core_1_1DB_1_1WP_1_1Users.html", null ],
    [ "PluginFrame\\Core\\Services\\Views", "classPluginFrame_1_1Core_1_1Services_1_1Views.html", null ],
    [ "PluginFrame\\Core\\Services\\Widgets\\Widget", "classPluginFrame_1_1Core_1_1Services_1_1Widgets_1_1Widget.html", null ]
];