name: WordPress Docs Deployment
on:
  push:
    branches: [master]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
          mkdir -p public public/assets

      - name: Copy Config Files
        run: |
          # Copy Doxygen config to root
          cp .github/docs_config/Doxyfile ./Doxyfile
          # Copy styling assets
          cp .github/docs_config/docs-header.html public/
          cp .github/docs_config/wordpress-docs.css public/
          cp .github/docs_config/assets/* public/assets/

      - name: Generate Documentation
        run: |
          echo "pf.ractstudio.com" > public/CNAME
          doxygen Doxyfile
          # Add WordPress footer
          echo '<div class="wp-docs-footer">Documentation follows <a href="https://developer.wordpress.org/coding-standards/">WordPress standards</a></div>' >> public/footer.html

      - name: Cleanup & Deploy
        run: rm Doxyfile  # Remove temporary file
      
      - name: Deploy to Doc Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: doc
          keep_files: true
          force_orphan: false