name: Plugin Frame Docs Deployment
on:
  push:
    branches: [master]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
          mkdir -p public

      - name: Copy Config Files
        run: |
          cp .github/Doxyfile ./Doxyfile
          cp -r .github/docs_config/* public/
          mkdir -p public/assets
          cp -r .github/docs_config/assets/* public/assets/

      - name: Verify Files
        run: ls -la public/

      - name: Generate Documentation
        run: |
          echo "pf.ractstudio.com" > public/CNAME
          doxygen Doxyfile

      - name: Cleanup
        run: rm Doxyfile
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: doc
          keep_files: true