# .github/workflows/docs.yml
name: Generate Docs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Doxygen Docs
        run: |
          sudo apt-get install doxygen
          doxygen Doxyfile
      - name: Deploy to GitHub Pages
        uses: ractstudio/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
